# Site
name: "TomorrowScale"
title: "TomorrowScale"
description: "The cutting edge of science and medicine."
logo: 'assets/images/tomorrowscale_logo_blk.png'
favicon: 'assets/images/tomorrowscale-logo.png'
baseurl: ''
google_analytics: 'UA-'
disqus: 'briggsly'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  briggs:
    name: briggs
    display_name: Justin Briggs
    gravatar: 5797288a8790b5766b631c2e68ca6800
    email: justin@tomorrowscale.com
    web: https://www.tomorrowscale.com
    twitter: https://twitter.com/briggsly
    description: "Creator and host @TomorrowScale podcast; DrugDev @Tetherex; Biology, Chemistry, Physics, Computation."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
